[package]
name = "l2book-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
linear_search_policy = []

[dependencies]
derivative = "2.2.0"
log = "0.4.20"

[profile.release]
lto = true
