on:
  push:
    branches:
      - master

name: Release

env:
  SEMVERBOT_VERSION: "1.3.1"

jobs:
  check:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/check-and-lint.yaml
  test:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/test.yaml
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - check
      - test
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Install semverbot
        run: |
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
          curl -o bin/sbot -L https://github.com/restechnica/semverbot/releases/download/v${SEMVERBOT_VERSION}/sbot-linux-amd64
          chmod +x bin/sbot
      - name: Update version
        run: |
          sbot update version
          current_version="$(sbot get version)"
          release_version="$(sbot predict version)"
          echo "CURRENT_VERSION=${current_version}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV
          echo "Current version: ${current_version}"
          echo "Next version: ${release_version}"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache dependencies
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Release build
        run: |
          cargo install cargo-edit
          cargo set-version ${RELEASE_VERSION}
          cargo build --release
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ env.PROJECT_NAME }}
#          path: target/release/${{ env.PROJECT_NAME }}
      - name: Create tag
        run: |
          sbot release version
          sbot push version
      - name: Generate release description
        run: |
          git log --oneline v${CURRENT_VERSION}..v${RELEASE_VERSION} > release.desc
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body_path: release.desc
          draft: false
          prerelease: false
